### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by mymindstorm** [MrLoLf/telekinesis-mod#2]
Hi @MrLoLf ,

Thanks for porting my mod! But, I noticed that you removed my name from the LICENSE file. Even though you have changed the orginial files related to the mod, you must properly attribute the source of that code by complying with the original LICENSE file.

Regards,
@mymindstorm

**Comment by MrLoLf** [comment]
I change the file back to the original but would a mention be enough for you, that the original mod is yours. Because I have changed a lot of the code and it is modified to fit the newer versions. So it's mostly a rewrite of your mod with the idea of your mod.

Best regards MrLoLf

**Comment by mymindstorm** [comment]
Feel free to add your name to the license file. It is just not ok to remove the old one since this is a fork.

**Comment by MrLoLf** [comment]
I hope you're fine with this version. I would close this issue now. Thanks for your issue opening.
